=== libogonek/unicode-data/cldr/dtd/ldmlSupplemental.dtd
<!--
Copyright Â© 2003-2005 Unicode, Inc. and others. All rights reserved. Distributed under the Terms of Use in http://www.unicode.org/copyright.html.

Permission is hereby granted, free of charge, to any person obtaining a copy of the Unicode data files and any associated documentation (the "Data Files") or Unicode software and any associated documentation (the "Software") to deal in the Data Files or Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, and/or sell copies of the Data Files or Software, and to permit persons to whom the Data Files or Software are furnished to do so, provided that (a) the above copyright notice(s) and this permission notice appear with all copies of the Data Files or Software, (b) both the above copyright notice(s) and this permission notice appear in associated documentation, and (c) there is clear notice in each modified Data File or in the Software as well as in the documentation associated with the Data File(s) or Software that the data or software has been modified.

THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA FILES OR SOFTWARE.

Except as contained in this notice, the name of a copyright holder shall not be used in advertising or otherwise to promote the sale, use or other dealings in these Data Files or Software without prior written authorization of the copyright holder.

    $Revision: 1.18 $
    $Date: 2005/05/25 08:40:36 $
-->

<!ELEMENT supplementalData ( version?, generation?, currencyData?, territoryContainment?, languageData?, timezoneData, characters?, metadata? ) >
<!ATTLIST supplementalData version CDATA #FIXED "1.3" >

<!ELEMENT version ( #PCDATA ) >
<!ATTLIST version number CDATA #REQUIRED >

<!ELEMENT generation EMPTY >
<!ATTLIST generation date CDATA #REQUIRED >

<!ELEMENT currencyData ( fractions*, region+ ) >
<!ATTLIST currencyData draft ( true | false ) #IMPLIED >

<!ELEMENT fractions ( info+ ) >
<!ATTLIST fractions draft ( true | false ) #IMPLIED >

<!ELEMENT info EMPTY >
<!ATTLIST info iso4217 NMTOKEN #REQUIRED >
<!ATTLIST info digits NMTOKEN #IMPLIED >
<!ATTLIST info rounding NMTOKEN #IMPLIED >
<!ATTLIST info draft ( true | false ) #IMPLIED >

<!ELEMENT region ( currency* ) >
<!ATTLIST region iso3166 NMTOKEN #REQUIRED >
<!ATTLIST region draft ( true | false ) #IMPLIED >

<!ELEMENT currency ( alternate* ) >
<!ATTLIST currency before NMTOKEN #IMPLIED > <!-- This usage is deprecated. Use from and to. -->
<!ATTLIST currency from NMTOKEN #IMPLIED >
<!ATTLIST currency to NMTOKEN #IMPLIED >
<!ATTLIST currency iso4217 NMTOKEN #REQUIRED >
<!ATTLIST currency draft ( true | false ) #IMPLIED >

<!ELEMENT alternate EMPTY > <!-- This usage is deprecated. Use from and to. -->
<!ATTLIST alternate iso4217 NMTOKEN #REQUIRED >

<!ELEMENT territoryContainment ( group* ) >
<!ELEMENT group EMPTY >
<!ATTLIST group type NMTOKEN #REQUIRED >
<!ATTLIST group contains NMTOKENS #IMPLIED >
<!ATTLIST group draft ( true | false ) #IMPLIED >

<!ELEMENT languageData ( language* ) >
<!ELEMENT language EMPTY >
<!ATTLIST language type NMTOKEN #REQUIRED >
<!ATTLIST language scripts NMTOKENS #IMPLIED >
<!ATTLIST language territories NMTOKENS #IMPLIED >
<!ATTLIST language variants NMTOKENS #IMPLIED >
<!ATTLIST language draft ( true | false ) #IMPLIED >
<!ATTLIST language alt NMTOKENS #IMPLIED >

<!ELEMENT timezoneData ( mapTimezones* ) >
<!ELEMENT mapTimezones ( mapZone* ) >
<!ATTLIST mapTimezones type NMTOKEN #REQUIRED >
<!ELEMENT mapZone EMPTY >
<!ATTLIST mapZone type CDATA #REQUIRED >
<!ATTLIST mapZone other CDATA #REQUIRED >

<!ELEMENT characters ( character-fallback*) >
<!ATTLIST characters draft ( true | false ) #IMPLIED >
<!ELEMENT character-fallback ( character* ) >
<!ELEMENT character (substitute*) >
<!ATTLIST character value CDATA #REQUIRED >
<!ATTLIST character draft ( true | false ) #IMPLIED >
<!ATTLIST character standard CDATA #IMPLIED >
<!ATTLIST character references CDATA #IMPLIED >
<!ATTLIST character alt CDATA #IMPLIED >
<!ELEMENT substitute (#PCDATA) >
<!ATTLIST substitute draft ( true | false ) #IMPLIED >
<!ATTLIST substitute standard CDATA #IMPLIED >
<!ATTLIST substitute references CDATA #IMPLIED >
<!ATTLIST substitute alt CDATA #IMPLIED >

<!ELEMENT metadata (  alias?, deprecated? ) >
<!ATTLIST metadata draft ( true | false ) #IMPLIED >

<!ELEMENT alias ( languageAlias*,  scriptAlias*, territoryAlias*, variantAlias* ) >
<!ATTLIST alias draft ( true | false ) #IMPLIED >

<!ELEMENT languageAlias EMPTY >
<!ATTLIST languageAlias type NMTOKEN #IMPLIED >
<!ATTLIST languageAlias replacement NMTOKEN #IMPLIED >

<!ELEMENT scriptAlias EMPTY >
<!ATTLIST scriptAlias type NMTOKEN #IMPLIED >
<!ATTLIST scriptAlias replacement NMTOKEN #IMPLIED >

<!ELEMENT territoryAlias EMPTY >
<!ATTLIST territoryAlias type NMTOKEN #IMPLIED >
<!ATTLIST territoryAlias replacement NMTOKEN #IMPLIED >

<!ELEMENT variantAlias EMPTY >
<!ATTLIST variantAlias type NMTOKEN #IMPLIED >
<!ATTLIST variantAlias replacement NMTOKEN #IMPLIED >

<!ELEMENT deprecated ( deprecatedItems* ) >
<!ATTLIST deprecated draft ( true | false ) #IMPLIED >

<!ELEMENT deprecatedItems EMPTY >
<!ATTLIST deprecatedItems draft ( true | false ) #IMPLIED >
<!ATTLIST deprecatedItems type ( standard | supplemental ) #IMPLIED >
<!ATTLIST deprecatedItems elements NMTOKENS #IMPLIED >
<!ATTLIST deprecatedItems attributes NMTOKENS #IMPLIED >
<!ATTLIST deprecatedItems values CDATA #IMPLIED >

=== libogonek/unicode-data/cldr/supplemental/supplementalData.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE supplementalData SYSTEM "http://www.unicode.org/cldr/dtd/1.3/ldmlSupplemental.dtd">
<supplementalData version="1.3">
	<version number="$Revision: 1.44 $"/>
	<generation date="$Date: 2005/05/23 17:17:49 $"/>
    <currencyData draft="true">
        <fractions>
            <info iso4217="ADP" digits="0" rounding="0"/>
            <info iso4217="BHD" digits="3" rounding="0"/>
            <info iso4217="BIF" digits="0" rounding="0"/>
            <info iso4217="BYR" digits="0" rounding="0"/>
            <info iso4217="CHF" digits="2" rounding="5"/>
            <info iso4217="CLF" digits="0" rounding="0"/>
            <info iso4217="CLP" digits="0" rounding="0"/>
            <info iso4217="DEFAULT" digits="2" rounding="0"/>
            <info iso4217="DJF" digits="0" rounding="0"/>
            <info iso4217="ESP" digits="0" rounding="0"/>
            <info iso4217="GNF" digits="0" rounding="0"/>
            <info iso4217="IQD" digits="3" rounding="0"/>
            <info iso4217="ITL" digits="0" rounding="0"/>
            <info iso4217="JOD" digits="3" rounding="0"/>
            <info iso4217="JPY" digits="0" rounding="0"/>
            <info iso4217="KMF" digits="0" rounding="0"/>
            <info iso4217="KRW" digits="0" rounding="0"/>
            <info iso4217="KWD" digits="3" rounding="0"/>
            <info iso4217="LYD" digits="3" rounding="0"/>
            <info iso4217="MGA" digits="0" rounding="0"/><!-- Is this right? -->
            <info iso4217="MGF" digits="0" rounding="0"/>
            <info iso4217="OMR" digits="3" rounding="0"/>
            <info iso4217="PYG" digits="0" rounding="0"/>
            <info iso4217="RWF" digits="0" rounding="0"/>
            <info iso4217="TND" digits="3" rounding="0"/>
            <info iso4217="TRL" digits="0" rounding="0"/>
            <info iso4217="VUV" digits="0" rounding="0"/>
            <info iso4217="XAF" digits="0" rounding="0"/>
            <info iso4217="XOF" digits="0" rounding="0"/>
            <info iso4217="XPF" digits="0" rounding="0"/>
        </fractions>
<!--
Note: When reading these dates, you should read them as inclusive date ranges.
The date ranges are like date ranges that you see on tomb stones,
but some dates are approximate. Some date ranges overlap due to
revolts, invasions, new constitutions, and slow planned adoption of new currency.
The length of time for these change overs vary widely. 
Sometimes, hyperinflation will cause more than one currency to be in effect
in one year. Dates without a "to" attribute mean that the currency is still
in use.

Dates try to use ISO-8601 style dates, and be accurate as possible.
They are usually in one of the following formats.
yyyy-MM-dd
yyyy-MM
yyyy

It is also worth noting this as a part of the history of ISO-4217. This
should be kept in mind in case anyone is claiming that an ISO code existed
before 1978 (source: www.unece.org):
... the International Organization for Standardization (ISO) decided in 1973 to
develop a code for the representation of currencies and funds for use in any
application of trade, commerce or banking. ... At its seventeenth session
(February 1978) the Group of Experts agreed that the three-letter alphabetic
codes for International Standard ISO 4217, "Codes for the representation of
currencies and funds", would be suitable for use in international trade.

Most of this list was derived from the following sources: 
http://www.iso.org/iso/en/prods-services/popstds/currencycodeslist.html
http://www.globalfindata.com/gh/index.html
http://europa.eu.int/comm/translation/currencies/entable1.htm
http://europa.eu.int/comm/budget/inforeuro/index.cfm?fuseaction=countries&Language=en
http://www.unece.org/cefact/recommendations/rec09/rec09_ecetrd203.pdf
The printed version of ISO-4217:2001
-->
        <region iso3166="830">
            <currency iso4217="GBP" from="1694-07-27"/>
        </region>
        <region iso3166="833">
            <currency iso4217="GBP" from="1694-07-27"/>
        </region>
        <region iso3166="AD">
            <currency iso4217="EUR" from="1999-01-01"/>
            <currency iso4217="ESP" from="1873" to="2002-02-28"/>
            <currency iso4217="FRF" from="1960-01-01" to="2002-02-17"/>
            <currency iso4217="ADP" from="1936" to="2001-12-31"/><!-- End date from europa.eu.int. -->
            <!-- currency iso4217="ADD" from="1873" to="2002-02-28"/ --><!-- Not listed in the 2001 list -->
        </region>
        <region iso3166="AE">
            <currency iso4217="AED" from="1973-05-19"/>
        </region>
        <region iso3166="AF">
            <currency iso4217="AFN" from="2002-10-07"/>
            <currency iso4217="AFA" from="1927-03-14" to="2002-12-31"/>
            <!-- Other currencies sort of existed under different Afghan governments before 2003,
                 but they weren't registered with ISO-4217. -->
        </region>
        <region iso3166="AG">
            <currency iso4217="XCD" from="1965-10-06"/>
        </region>
        <region iso3166="AI">
            <currency iso4217="XCD" from="1965-10-06"/>
        </region>
        <region iso3166="AL">
            <currency iso4217="ALL" from="1965-08-16"/>
        </region>
        <region iso3166="AM">
            <currency iso4217="AMD" from="1993-11-22"/>
            <currency iso4217="RUR" from="1991-12-25" to="1993-11-22"/>
            <currency iso4217="SUR" from="1961-01-01" to="1991-12-25"/>
        </region>
        <region iso3166="AN">
            <currency iso4217="ANG" from="1940-05-10"/>
        </region>
        <region iso3166="AO">
            <currency iso4217="AOA" from="1999-12-13"/>
            <currency iso4217="AOR" from="1995-07-01" to="2000-02"/>
            <currency iso4217="AON" from="1990-09-25" to="2000-02"/>
            <currency iso4217="AOK" from="1977-01-08" to="1991-03"/>
        </region>
        <region iso3166="AQ">
	<currency iso4217="XXX"/>
            <!-- This is Antarctica. It has no currency -->
        </region>
        <region iso3166="AR">
            <currency iso4217="ARS" from="1992-01-01"/>
            <currency iso4217="ARA" from="1985-06-14" to="1992-01-01"/>
            <currency iso4217="ARP" from="1983-06-01" to="1985-06-14"/>
        </region>
        <region iso3166="AS">
            <currency iso4217="USD" from="1904-07-16"/>
        </region>
        <region iso3166="AT">
            <currency iso4217="EUR" from="1999-01-01"/>
            <currency iso4217="ATS" from="1947-12-04" to="2002-02-28"/>
        </region>
        <region iso3166="AU">
            <currency iso4217="AUD" from="1966-02-14"/>
        </region>
        <region iso3166="AW">
            <currency iso4217="AWG" from="1986-01-01"/>
            <currency iso4217="ANG" from="1940-05-10" to="1986-01-01"/>
        </region>
        <region iso3166="AX"><!-- An autonomous and demilitarized province/islands of Finland -->
            <currency iso4217="EUR" from="1999-01-01"/>
        </region>
        <region iso3166="AZ">
            <currency iso4217="AZM" from="1993-11-22"/>
            <currency iso4217="RUR" from="1991-12-25" to="1994-01-01"/>
            <currency iso4217="SUR" from="1961-01-01" to="1991-12-25"/>
        </region>
        <region iso3166="BA">
            <currency iso4217="BAM" from="1995-01-01"/>
            <!-- currency iso4217="BAN" from="1994-08-15" to="1997-07"/ --><!-- Not listed in the 2001 list -->
            <currency iso4217="BAD" from="1992-07-01" to="1997-07"/>
            <!-- currency iso4217="YUR" from="1992-07-01" to="1993-10-01"/ --><!-- Not listed in the 2001 list -->
            <currency iso4217="YUN" from="1990-01-01" to="1992-07-01"/>
            <currency iso4217="YUD" from="1966-01-01" to="1990-01-01"/>
        </region>
        <region iso3166="BB">
            <currency iso4217="BBD" from="1973-12-03"/>
            <currency iso4217="XCD" from="1965-10-06" to="1973-12-03"/>
        </region>
        <region iso3166="BD">
            <currency iso4217="BDT" from="1972-01-01"/>
            <currency iso4217="PKR" from="1948-04-01" to="1972-01-01"/>
            <currency iso4217="INR" from="1835-08-17" to="1948-04-01"/>
        </region>
        <region iso3166="BE">
            <currency iso4217="EUR" from="1999-01-01"/>
            <currency iso4217="BEF" from="1831-02-07" to="2002-02-28"/>
            <currency iso4217="NLG" from="1816-12-15" to="1831-02-07"/>
        </region>
        <region iso3166="BF">
            <currency iso4217="XOF" from="1984-08-04"/>
        </region>
        <region iso3166="BG">
            <currency iso4217="BGN" from="1999-07-05"/>
            <currency iso4217="BGL" from="1962-01-01" to="1999-07-05"/>
        </region>
        <region iso3166="BH">
            <currency iso4217="BHD" from="1965-10-16"/>
        </region>
        <region iso3166="BI">
            <currency iso4217="BIF" from="1964-05-19"/>
        </region>
        <region iso3166="BJ">
            <currency iso4217="XOF" from="1975-11-30"/>
        </region>
        <region iso3166="BM">
            <currency iso4217="BMD" from="1970-02-06"/>
        </region>
        <region iso3166="BN">
            <currency iso4217="BND" from="1967-06-12"/>
            <currency iso4217="MYR" from="1963-09-16" to="1967-06-12"/>
        </region>
        <region iso3166="BO">
            <currency iso4217="BOB" from="1987-01-01"/>
            <currency iso4217="BOP" from="1963-01-01" to="1986-12-31"/>
            <!-- currency iso4217="BOL" from="1863-06-23" to="1962-12-31"/ --><!-- Not listed in the 2001 list -->
        </region>
        <region iso3166="BR">
            <currency iso4217="BRL" from="1994-07-01"/>
